# Form implementation generated from reading ui file 'tasks_design.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(409, 610)
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 391, 594))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tasksList = QtWidgets.QListWidget(parent=self.widget)
        self.tasksList.setObjectName("tasksList")
        self.verticalLayout_2.addWidget(self.tasksList)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.filterCategory = QtWidgets.QComboBox(parent=self.widget)
        self.filterCategory.setObjectName("filterCategory")
        self.horizontalLayout_2.addWidget(self.filterCategory)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.taskTitle = QtWidgets.QLineEdit(parent=self.widget)
        self.taskTitle.setObjectName("taskTitle")
        self.verticalLayout_2.addWidget(self.taskTitle)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.taskDescription = QtWidgets.QTextEdit(parent=self.widget)
        self.taskDescription.setObjectName("taskDescription")
        self.verticalLayout_2.addWidget(self.taskDescription)
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectCategory = QtWidgets.QComboBox(parent=self.widget)
        self.selectCategory.setObjectName("selectCategory")
        self.horizontalLayout.addWidget(self.selectCategory)
        self.categoriesButton = QtWidgets.QPushButton(parent=self.widget)
        self.categoriesButton.setObjectName("categoriesButton")
        self.horizontalLayout.addWidget(self.categoriesButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.addTaskButton = QtWidgets.QPushButton(parent=self.widget)
        self.addTaskButton.setObjectName("addTaskButton")
        self.verticalLayout.addWidget(self.addTaskButton)
        self.deleteTaskButton = QtWidgets.QPushButton(parent=self.widget)
        self.deleteTaskButton.setObjectName("deleteTaskButton")
        self.verticalLayout.addWidget(self.deleteTaskButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Список задач"))
        self.label.setText(_translate("Form", "Фильтр по категориям:"))
        self.label_2.setText(_translate("Form", "Название задачи"))
        self.label_3.setText(_translate("Form", "Описание"))
        self.label_4.setText(_translate("Form", "Категория"))
        self.categoriesButton.setText(_translate("Form", "Категории"))
        self.addTaskButton.setText(_translate("Form", "Добавить задачу"))
        self.deleteTaskButton.setText(_translate("Form", "Удалить задачу"))
